export const SERVER_URL = "http://localhost:8090"
export const REGISTER = "/auth/register"
export const LOGIN = "/auth/login"
export const ACCOUNT_INFO = "account/account-info"
export const CREATE_ORDER = "/order/create-order"
export const ORDER_BY_ACCOUNT = "/order/order-by-account"
